[package]
name = "actix_telepathy_derive"
version = "0.1.0"
authors = ["wenig <info@pwenig.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
log = "0.4"
syn = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_yaml = "0.8"
